lacework/python-sdk

.github/workflows/python-test.yml
Serializing testing for python versions due to "[400] Bad Request - Error: Cannot create policy ***-default-XXX because it already exists in database." errors when creating queries/policies.
=> ci: serialize testing for different python versions

jupyter/docker/docker-build.yml, jupyter/docker/docker_build/Dockerfile
To make the docker hub page more readable it's better to change the build context to the jupyter folder.
=> Changed the docker build context 

laceworksdk/api/queries.py
For newer data sources the evaluator ID should not be set. It needs to be set for cloud trail events, but not for agent datasets (see [here](https://zd-md-src-m.netlify.app/1500005358042.html#write-the-initial-query)).
This PR checks to see if the `evaluator_id` is set and only if it is set adds it to the JSON data sent to the API. If it is empty or `None` it will omit it from the data sent to the API.
=> Omitting evaluator ID if not set in LQL execute queries.

jupyter/MANIFEST.in, jupyter/docker/docker_build/00-import.py, jupyter/docker/docker_build/lacework/main.js, jupyter/docker/docker_build/snippets.json, jupyter/laceworkjupyter/__init__.py, jupyter/laceworkjupyter/decorators.py, jupyter/laceworkjupyter/features/__init__.py, jupyter/laceworkjupyter/features/client.py, jupyter/laceworkjupyter/features/query.py, jupyter/laceworkjupyter/features/query.yaml, jupyter/laceworkjupyter/helper.py, jupyter/laceworkjupyter/manager.py, jupyter/laceworkjupyter/utils.py, jupyter/laceworkjupyter/version.py, jupyter/notebooks/colab_sample.ipynb, jupyter/requirements.txt, jupyter/setup.py, laceworksdk/api/policies.py
Made quite a few changes to the Jupyter notebook assistant:
- Adding a Lacework ctx (context) that is passed along if needed
- Adding a manager to better handle registration of new helper functions
- Moved the SDK wrapper to a separate client file
- The new main touching point of the notebook is an object that contains a context and can call functions or features
- Adding a new concept of `features`, which ties to the main notebook object that provides additional functionality
- Added two features, one for getting a new client and the other to run pre-defined LQL queries to gather more context
- Updated the notebook container to take advantage of these new features
=> Changed the Jupyter helper, adding ability to define helper functions

laceworksdk/api/policies.py
Similar to what was done in queries, we need to make the evaluator_id optional.
=> Made the evaluator ID optional for policies.

jupyter/docker/docker_build/00-import.py, jupyter/laceworkjupyter/accessors.py, jupyter/tests/laceworkjupyter/test_accessors.py, tests/api/v2/test_agent_access_tokens.py
Added a file called `accessors.py` that defines custom accessors to pandas DataFrame.
The first version included a simple decode class that can define various decoding methods, to begin with just URL unquote and base64 decoding. Also an encoder, that only does base64 encoding ATM.
Example usage:
```
df['base_decoded'] = df.base.decode.base64()
```
In this case you've got a dataframe that is stored in a variable called `df`. You can then call the accessor `decode` and use any of the defined functions there, for instance the base64, which is a series accessor. In this case it would take a column in the dataframe `df` called `base` and run the decode accessor `base64` on the series object (df.base produces a pandas Series for the column `base`).
Similar to:
```
df['uri_expanded'] = …
```
=> Added custom dataframe accessors.

jupyter/laceworkjupyter/features/__init__.py, jupyter/laceworkjupyter/features/hunt.py, jupyter/laceworkjupyter/features/query_builder.py, jupyter/laceworkjupyter/features/utils.py
This PR introduces few changes:
+ Custom queries are now a separate feature, accessible via `lw.query_builder()`
+ Changes made to the custom queries:
+ Allows you to select which matching behaviour you want (see picture below)
+ Adds in number support
+ Removes timestamp from filters
+ Few minor improvements
+ Adds in JSON support.
+ Cloud hunt still has the custom query builder as an option.
Example UI:
And examples filters filled in
=> Custom Queries are now a separate feature

jupyter/laceworkjupyter/accessors.py
This PR adds a simple class that adds an IP accessor to dataframes in the notebook environment.
They can be accessed with `df.my_column.ip.X` 
This PR only implements a single accessor, `reverse_dns` can be used:
```python
my_frame['reverse_host'] = my_frame['ip_address'].ip.reverse_dns()
```
=> Added an IP accessor with a reverse DNS function.

jupyter/docker/docker_build/00-import.py, jupyter/docker/docker_build/jupyter_notebook_config.py, jupyter/laceworkjupyter/features/__init__.py, jupyter/laceworkjupyter/features/helper.py, jupyter/laceworkjupyter/features/utils.py
This is a PR that adds a simple `feature` into the lw object to extract data from data frames that contain JSON structs.
Example use case:
```python
df['os'] = lw.deep_extract_field(df, 'properties', 'user_agent.extracted_values.os')
```
Would extract the `os` field from a JSON struct that that would look like
```python
{
'user_agent': {
'extracted_values': {
'os': 'myhost_os'
},
},
}
```
=> Added a helper to extract data from JSON structs inside data frames

jupyter/laceworkjupyter/features/mitre.py, jupyter/laceworkjupyter/features/mitre.yaml
This PR makes considerably changes to the Mitre ATT&CK integration. It extends the support of the YAML file to include more flexible matching between Mitre IDs and ATT&CK techniques.
Instead of having a simple 1:1 matching between alertType it is now flexible which column to choose, and you can combine the content of multiple columns to generate the filter for the matching.
=> Made changes to the Mitre ATT&CK Integration

laceworksdk/http_session.py
This PR is meant to resolve #72 - This will remove the base domain if it was provided with the `account` parameter.  This prevents duplication of the base domain which would result in DNS resolution issues during initialization.
=> fix: sanitize the provided account name

jupyter/laceworkjupyter/plugins/alerts.py
There was a bug in the special handling of the Alerts API, the logic was created for an older version of the API that was in testing.
=> Bug fix for Alerts API in Jupyter

laceworksdk/api/base_endpoint.py
Found that the AWS CloudTrail Org-level integration uses a combination of lowerCamelCase and snake_case... 🤦 
https://docs.lacework.com/onboarding/setup-of-organization-aws-cloudtrail-integration#account-mapping-file
=> fix: allow exclusions to lower camel case conversion

jupyter/laceworkjupyter/helper.py, jupyter/laceworkjupyter/plugins/alerts.py, tests/api/v2/test_vulnerability_policies.py
Fixed an issue in API V2 where APIs are subclasses of other classes, eg `.activities.dns`, etc... this PR makes sure to traverse the sub classes as well, one layer deeper to register the API wrapper accordingly.
=> (fix) fixed and issue for subclasses containing API calls in Jupyter notebook

jupyter/docker/docker_build/00-import.py
The TS API client has not yet upgraded the now deprecated OOB flow in Oauth, causing it to fail when attempting to import, and therefore having cascading effects on the jupyter notebook environment (which loads the TS client as part of other libraries)... disabling the dependencies for now
TS bug: https://github.com/google/timesketch/issues/2388
=> (fix) a bug in TS API client prevents the notebook from loading.

laceworksdk/http_session.py
Adding a logger warning to indicate that APIv1 is being deprecated at the end of Dec 2022.
=> chore: log deprecation warning for APIv1 usage

jupyter/laceworkjupyter/helper.py, laceworksdk/api/__init__.py, laceworksdk/http_session.py
Making subaccounts more easily visible in the HTTP session, API client as well as in the jupyter client.
ATM some of this is done today by using access to private variables within classes, which is not an ideal way of doing things, this way the classes expose the subaccount intentionally as a property, that can be modified
=> feat: making it easer to see and set subaccounts

jupyter/laceworkjupyter/helper.py
After the subaccount property was added to the SDK the jupyter wrapper now stores the api wrapper object as a property of the helper, this is a fix to make sure we don't do that.
=> (fix) a bug where subaccounts got set on the jupyter object.

laceworksdk/api/__init__.py, laceworksdk/http_session.py
This PR moves the `account` parameter validation to the instantiation of the `laceworksdk` object, rather than doing it in the http session.
=> fix: moving account validation to SDK object instantiation

laceworksdk/api/__init__.py
- This PR aims to prevent loading a subaccount parameter from config files if an account was provided either directly or through an environment variable.
=> fix: only load subaccount data from config file when required

laceworksdk/api/v2/alerts.py
Hey @tmac1973!  Thanks for proposing a PR for this - if my memory serves, this endpoint was originally released without pagination.  So, as you correctly pointed out, I was hesitant to migrate it to the paginated endpoint  of returning a generator simply to prevent breaking changes.
I made some slight changes to your PR so that there's an imposed limit on the alerts by default.  This should mean that the functionality wont change for any previous implementations, but still allows the user to specify a higher upper-bound.  Two main reasons I'd like to do things this way:
- If there are a lot of results, it can take a long time to iterate through many pages.
- The dataset that gets returned can become pretty massive.
Happy to consider a higher default if you think it's necessary.
=> fix: pagination updates for the alerts endpoint

examples/example_team_users.py, laceworksdk/api/__init__.py, laceworksdk/api/v2/team_users.py, laceworksdk/api/v2/user_groups.py, laceworksdk/http_session.py, tests/api/v2/test_team_users.py, tests/api/v2/test_user_groups.py
Enable managing users with the new, experimental, TeamUsers and UserGroups API
=> feat: add support for TeamUsers and UserGroups APIs

.github/workflows/python-test.yml, tests/api/v2/test_alert_channels.py, tests/api/v2/test_resource_groups.py
Summary:
Slack alert did not include link to workflow run. 
ResourceGroupV2  beta flag is turned on in techally test environment causing one of those tests to fail. Marking that test as "flakey" for now. Opening separate issue to fix
Some AlertChannel test are failing randomly with a 404. Marking "flakey" for now and opening separate issue to investigate. 
Issue:
=> test: fix slack alerting and mark some tests as flakey

.github/workflows/python-lint.yml, .github/workflows/python-test.yml, poetry.lock, pyproject.toml, pytest.ini, tests/api/test_crud_endpoint.py, tests/api/v2/test_agent_access_tokens.py, tests/api/v2/test_agent_info.py, tests/api/v2/test_alert_channels.py, tests/api/v2/test_alert_profiles.py, tests/api/v2/test_alert_rules.py, tests/api/v2/test_cloud_accounts.py, tests/api/v2/test_container_registries.py, tests/api/v2/test_data_export_rules.py, tests/api/v2/test_datasources.py, tests/api/v2/test_events.py, tests/api/v2/test_inventory.py, tests/api/v2/test_organization_info.py, tests/api/v2/test_policy_exceptions.py, tests/api/v2/test_queries.py, tests/api/v2/test_report_definitions.py, tests/api/v2/test_report_rules.py, tests/api/v2/test_resource_groups.py, tests/api/v2/test_team_members.py, tests/api/v2/test_team_users.py, tests/api/v2/test_user_groups.py, tests/api/v2/test_vulnerability_exceptions.py, tests/api/v2/test_vulnerability_policies.py
Summary:
Seeing random failures due to race condition in which "get_by_guid" test would still return deleted object after delete call, causing subsequent "get details" call to fail with 404. 
Details:
Add pytest-order and ensure that delete test always runs last for any given endpoint
Disable slack alerting until tests are working for sure.
Issue:
=> test: fix race condition with delete tests

docs-source/conf.py, laceworksdk/api/base_endpoint.py, laceworksdk/api/crud_endpoint.py, laceworksdk/api/read_endpoint.py, laceworksdk/api/search_endpoint.py, laceworksdk/api/v2/alert_channels.py, laceworksdk/api/v2/alerts.py, laceworksdk/api/v2/audit_logs.py, laceworksdk/api/v2/cloud_activities.py, laceworksdk/api/v2/contract_info.py, laceworksdk/api/v2/datasources.py, laceworksdk/api/v2/inventory.py, laceworksdk/api/v2/organization_info.py, laceworksdk/api/v2/policies.py, laceworksdk/api/v2/policy_exceptions.py, laceworksdk/api/v2/queries.py, laceworksdk/api/v2/report_definitions.py, laceworksdk/api/v2/reports.py, laceworksdk/api/v2/schemas.py, laceworksdk/api/v2/user_groups.py, laceworksdk/api/v2/user_profile.py, laceworksdk/api/v2/vulnerabilities.py, pyproject.toml
These should have been private. This change fixes this which is required for the auto api doc generator to keep these methods out of the API docs.
Testing:
Ran tests locally, all passed
Issue:
https://lacework.atlassian.net/browse/GROW-2671
=> refactor: Make base classmethods private

laceworksdk/api/crud_endpoint.py
It indicates a generator as a return type when it is actually a dict
Issue:
https://lacework.atlassian.net/browse/GROW-2686
=> docs: fix CRUD search method docstring

laceworksdk/api/search_endpoint.py, tests/api/test_search_endpoint.py
kwargs are not passed to initial POST but are passed to subsequent pagination GET calls, causing crashes. Remove kwargs since they were never implemented in a working state for the search method.
Issue:
https://lacework.atlassian.net/browse/GROW-2684
=> fix: Search class passes kwargs to pagination GET

.github/workflows/python-test-quarantine.yml, poetry.lock, pyproject.toml, tests/api/v2/test_alert_channels.py, tests/api/v2/test_alerts.py, tests/api/v2/test_contract_info.py, tests/api/v2/test_events.py, tests/api/v2/test_policy_exceptions.py, tests/api/v2/test_report_definitions.py, tests/api/v2/test_reports.py, tests/api/v2/test_resource_groups.py
Summary: 
There are a number of tests put into the "flakey" group because they fail intermittently. Fix the ones that can be fixed and rename the "flakey" group to "quarantine" to avoid confusion with the "flaky" tag provided by pytest which is a a similar but not identical thing. 
Testing:
Ran all the tests successfully multiple times except for the single quarantined. 
Since these are intermittent though I will watch nightly tests for a while to ensure they are truly fixed before I turn on slack alerting again. 
Issue:
https://lacework.atlassian.net/browse/GROW-2664
=> test: review, fix, and rename "flakey" tests

tests/api/v2/test_alerts.py
removed "timeline" scope from Alerts test because get_by_guid test failing due to most alert guids not supporting timeline scope
issue: 
https://lacework.atlassian.net/browse/GROW-2664
=> test: fix testAlerts failures

tests/api/v2/test_alerts.py
Cannot test closing an alert if no open alerts exist. 
Issue:
https://lacework.atlassian.net/browse/GROW-2664
=> test: testing alert close requires open alerts 

tests/api/v2/test_resource_groups.py
Resource groups V2 changes the return schema for some objects. This adds logic to work around that for now as V2 appears to be a work in progress.
issue:
https://lacework.atlassian.net/browse/GROW-2663
=> test: fix resourceGroup test for RGv2

.github/workflows/python-release.yml
Poetry needs to be installed as part of the github action for semantic release
Issue: 
https://lacework.atlassian.net/browse/GROW-2746
=> ci: add poetry to release action

.github/workflows/python-release.yml
version command was missing from the release workflow branch for minor releases.
=> ci(release): add version command to release action

.github/workflows/python-release.yml
Start to move changelog generation out of release action and into push action to avoid bumping up against main branch protection
=> ci(release): remove commit of repo to main in GH release action

.github/workflows/python-test.yml, tests/api/v2/test_agent_access_tokens.py, tests/api/v2/test_alert_profiles.py, tests/api/v2/test_alert_rules.py, tests/api/v2/test_alerts.py, tests/api/v2/test_container_registries.py, tests/api/v2/test_data_export_rules.py, tests/api/v2/test_policies.py, tests/api/v2/test_policy_exceptions.py, tests/api/v2/test_queries.py, tests/api/v2/test_report_definitions.py, tests/api/v2/test_report_rules.py, tests/api/v2/test_resource_groups.py, tests/api/v2/test_team_members.py, tests/api/v2/test_team_users.py, tests/api/v2/test_vulnerability_exceptions.py, tests/api/v2/test_vulnerability_policies.py
Some tests fail because:
- Objects are randomly selected and not all object types are suitable for all tests ( e.g. you can't close some alerts )
- Object deletion is asynchronous resulting in the API returning a "GET" with containing an object thats already been deleted. This causes issues when attempting to get details on a deleted object
Solution: 
Automatically retry some tests if they fail.
=> test: retry failing tests and enable slack notification

.github/workflows/python-release.yml
Added token that allows push to main for changelog.MD. 
Also split up action into multiple steps.
=> ci(release): allow release action to push changelog

.github/workflows/python-test.yml
=> ci: send alerts to Slack only from `main` branch (#170)

.github/workflows/python-test.yml, laceworksdk/api/v2/vulnerabilities.py, tests/api/v2/test_vulnerabilities.py
Summarazies image details on all the evaluations in a given time range.
POST https://YourLacework.lacework.net/api/v2/Vulnerabilities/ImageSummary/search
Lacework highly recommends specifying a time range. Without a specified time range, the request uses the default time range of 24 hours prior to the current time. The maximum time range per API request is 7 days. To use the current time as the end time, exclude the endTime field.
You can optionally filter Images for active containers only by adding ndvContainers  field
{ "timeFilter": { "startTime": "2021-08-28T20:30:00Z", "endTime": "2021-08-28T22:30:00Z"}, "filters": [ { "field": "ndvContainers", "expression": "gt", "value": 0} ] }
=> Support Image Summary API for Box
