lacework/python-sdk

- laceworksdk/exceptions.py
- laceworksdk/http_session.py
- Implemented automatic retries when receiving a 500, 502, or 504 response.
- Improved exception handling logic to handle edge cases
> Added automatic retries for specific HTTP response codes.

- laceworksdk/http_session.py
> fix: Potentially uncaught exception in access token request

- laceworksdk/api/alert_channels.py
- tests/api/v1/test_suppressions.py
- tests/api/v2/test_alert_channels.py
- tests/api/v2/test_alert_rules.py
- tests/api/v2/test_report_rules.py
- Implemented Alert Channel 'Test' endpoint
- Updated tests for Alert/Report Rules for new filter format
> Updates for Lacework v3.92

- laceworksdk/api/alert_channels.py
- laceworksdk/api/alert_rules.py
- laceworksdk/api/audit_logs.py
- laceworksdk/api/policies.py
- laceworksdk/api/report_rules.py
- tests/api/v2/test_policies.py
- tests/api/v2/test_queries.py
- fix: removed `policy_ui` parameters for compatibility
- fix: cleanup for HTTP 204 response on search endpoints
- refactor: readability improvements for tests
> Updates for Lacework v4.20

- jupyter/README.md
- jupyter/docker/docker-compose.yml
- jupyter/docker/docker_build/Dockerfile
- jupyter/laceworkjupyter/__init__.py
- jupyter/laceworkjupyter/utils.py
- jupyter/notebooks/colab_sample.ipynb
- jupyter/notebooks/sample_notebook.ipynb
- laceworksdk/api/__init__.py
This PR adds the following things:
1. Sample notebooks
2. Badges to docker README to explain how to setup a docker container
3. Ability to select sections in the TOML file for access configuration
4. New options for the data frame flattening
> Added sample notebooks, badges to docker README and minor changes to helper.

- jupyter/laceworkjupyter/features/__init__.py
- jupyter/laceworkjupyter/features/client.py
- jupyter/laceworkjupyter/features/date.py
- jupyter/laceworkjupyter/features/query.py
Few bugfixes in the new Jupyter helper.
Also adding in a new quick helper for the parsing of date offsets, to have included in the lw. object for easier access
> Fixed an issue with fetching a new client.

- .github/workflows/python-test-flaky.yml
- .github/workflows/python-test.yml
- jupyter/README.md
- jupyter/laceworkjupyter/__init__.py
- jupyter/laceworkjupyter/features/__init__.py
- jupyter/laceworkjupyter/features/date.py
- jupyter/laceworkjupyter/features/filters.yaml
- jupyter/laceworkjupyter/features/hunt.py
- jupyter/laceworkjupyter/features/tables.yaml
- jupyter/laceworkjupyter/features/utils.py
- jupyter/laceworkjupyter/helper.py
- jupyter/laceworkjupyter/utils.py
- jupyter/laceworkjupyter/version.py
- jupyter/requirements.txt
- jupyter/setup.py
- jupyter/tests/laceworkjupyter/test_utils.py
- tests/api/v1/test_compliance.py
- tests/api/v1/test_integrations.py
- tests/api/v2/test_agent_access_tokens.py
- tests/api/v2/test_alert_rules.py
- tests/api/v2/test_audit_logs.py
- tests/api/v2/test_report_rules.py
This PR adds a new feature called `cloud_hunt`, which is an interactive UI built on ipywidgets that guides the user to generate LQL queries that can be used for threat hunting.
The PR also includes few bug fixes, and some additions to the LW context object.
The PR also splits out the tests into flaky and non-flaky, to make it easier to keep track on tests that often fail due to external reasons
Example of the UI inside a notebook:
The UI generates LQL queries to be generated and then verified/executed and results stored in a dataframe.
> Added a cloud hunt feature to the lacebook container

- jupyter/devtools/deploy_to_container.sh
- jupyter/laceworkjupyter/features/__init__.py
- jupyter/laceworkjupyter/features/policies.py
- jupyter/laceworkjupyter/features/utils.py
- tests/api/v2/test_alert_rules.py
Added a simple feature to expose the `client.queries.excecute_by_id` to the `lw` object to make it easier to discover.
> Added a simple feature exposing the running of stored LQL policies.

- jupyter/docker/docker_build/10-functions.py
- jupyter/laceworkjupyter/__init__.py
- jupyter/laceworkjupyter/accessors.py
- jupyter/laceworkjupyter/features/client.py
- jupyter/laceworkjupyter/features/date.py
- jupyter/laceworkjupyter/features/hunt.py
- jupyter/laceworkjupyter/features/policies.py
- jupyter/laceworkjupyter/manager.py
- jupyter/tests/laceworkjupyter/test_accessors.py
- pytest.ini
This PR introduces a simple decorator that can be used to register features, instead of the requirement to call the manager directly.
> Added a decorator to quickly register a function as a feature.

- jupyter/laceworkjupyter/features/filters.yaml
- jupyter/laceworkjupyter/features/hunt.py
- jupyter/laceworkjupyter/features/tables.yaml
- jupyter/laceworkjupyter/features/utils.py
This PR adds few things:
1. Few more table and filter definitions to the YAML files for pre-defined queries.
2. Ability to do custom queries based on the available datasources you've got.
3. Filter definitions can now be shared with more than a single table
> Added custom query building as well as few more defined functions.

- jupyter/laceworkjupyter/features/query_builder.py
This PR mainly makes minor cosmetic changes to the query builder feature.
It reduces the size of the text field, makes it possible to remove JSON filters that have been picked and reduces the width of the parameter label, to make things fit better in the display.
> Made minor cosmetic changes to the query builder.

- jupyter/docker/docker_build/Dockerfile
- jupyter/laceworkjupyter/features/query_builder.py
> Fixed a minor issue with the query builder, added dependencies to the docker build

- jupyter/docker/docker_build/Dockerfile
- jupyter/laceworkjupyter/features/__init__.py
- jupyter/laceworkjupyter/features/cache.py
- jupyter/laceworkjupyter/features/filters.yaml
- jupyter/laceworkjupyter/features/hunt.py
- jupyter/laceworkjupyter/features/join.yaml
- jupyter/laceworkjupyter/features/query.yaml
- jupyter/laceworkjupyter/features/query_builder.py
- jupyter/laceworkjupyter/features/tables.yaml
- jupyter/laceworkjupyter/features/utils.py
This PR adds JOIN supports into the query builder as well as a simple feature to quickly get values from the cache (context cache).
> Added JOIN support to the query builder.

- README.md
> docs: add Lacework logo to README.md

- jupyter/laceworkjupyter/decorators.py
- jupyter/laceworkjupyter/features/client.py
- jupyter/laceworkjupyter/plugins/__init__.py
- jupyter/laceworkjupyter/plugins/events.py
- jupyter/laceworkjupyter/plugins/evidence.py
- jupyter/laceworkjupyter/plugins/utils.py
- laceworksdk/api/__init__.py
- laceworksdk/api/v2/evidence.py
- tests/api/v2/test_activities.py
- tests/api/v2/test_alerts.py
This PR adds few things:
- EvidenceAPI into the SDK
- Support for the evidence API into Jupyter
- Support for paging into the Jupyter runbook
- Added a feature to gather evidence for a particular event.
> Added Evidence API as well as some improvements to the Jupyter project.

- laceworksdk/api/__init__.py
- laceworksdk/api/v2/agent_info.py
- laceworksdk/api/v2/inventory.py
- tests/api/v2/test_agent_info.py
- tests/api/v2/test_inventory.py
Adds support for AgentInfo & Inventory search endpoints
> Adding AgentInfo and Inventory endpoints

- laceworksdk/api/__init__.py
- laceworksdk/api/base_endpoint.py
- laceworksdk/api/v2/report_definitions.py
- tests/api/v2/test_report_definitions.py
Tests are marked as flaky until out of Beta
> feat: implemented new Report Definitions API endpoint

- jupyter/notebooks/colab_sample.ipynb
You can view the changes to the notebook [here](https://colab.research.google.com/github/lacework/python-sdk/blob/notebook_fix/jupyter/notebooks/colab_sample.ipynb)
> minor updates to example notebook to reflect API changes.

- laceworksdk/api/__init__.py
- laceworksdk/api/v2/agent_access_tokens.py
- laceworksdk/api/v2/data_export_rules.py
- laceworksdk/api/v2/user_groups.py
- laceworksdk/api/v2/vulnerability_exceptions.py
- tests/api/__init__.py
- tests/api/v2/test_data_export_rules.py
Summary:
The data export rules endpoint was not represented in the SDK
Testing:
Added integration tests and tested locally
Issue:
https://lacework.atlassian.net/browse/GROW-2613
> feat: Add support for data export rules endpoint

- tests/api/v2/test_alert_rules.py
- tests/api/v2/test_resource_groups.py
- tests/api/v2/test_user_groups.py
Search test failing for UserGroups due to change in API behavior
Search test failing for AlertRules due to edge case bug
> test: fix search test for AlertRules and UserGroups

- .github/workflows/python-test.yml
Summary: 
tests were failing with no notification 
Testing:
Really need to merge this to test it
Issue:
> chore: add slack notification for test failure

- .github/workflows/python-test.yml
> chore: fix indent in workflow yaml

- .github/workflows/python-test-flaky.yml
- .github/workflows/python-test.yml
Summary:
Needed to add latest python versions to tests
Issue:
https://lacework.atlassian.net/browse/GROW-2615
> chore: update tests to include all current python versions

- .github/workflows/python-lint.yml
- .github/workflows/python-test.yml
- poetry.lock
- pyproject.toml
Summary: 
Add ruff docstring linting and create GH action to lint for all pushes, not just for PRs and nightlies
Issue:
https://lacework.atlassian.net/browse/GROW-2625
> test: add docstring linting and move to separate action

- README.md
- docs-source/.gitignore
- docs-source/index.rst
- docs-source/static/authentication.rst
- docs-source/static/installation.rst
- docs-source/static/overview.rst
- docs-source/static/timestamps.rst
- docs-source/static/troubleshooting.rst
- docs-source/static/usage.rst
This documentation augments the autogenerated API docs.
> docs: Add handcrafted documentation

- .github/workflows/docs.yml
- .github/workflows/python-lint.yml
- .github/workflows/python-publish.yml
- .github/workflows/python-test-flaky.yml
- .github/workflows/python-test.yml
- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
Add poetry lockfile checks for git pre-commit and workflows
Addresses issues described here:
https://blog.phylum.io/bad-beat-poetry/
Issue:
https://lacework.atlassian.net/browse/GROW-1618
> tests: put lockfile checks in place to detect tampering

- docs-source/static/usage.rst
- examples/example_active_container_vulnerabilities.py
- examples/example_alerts.py
- examples/example_audit_logs.py
- examples/example_cloud_accounts.py
- examples/example_cloud_activities.py
- examples/example_query_policy.py
- examples/example_reports.py
- examples/example_syscall_query_policy.py
- examples/example_tokens.py
- examples/example_vulnerabilities.py
Many of the example scripts did not work. They do now. 
https://lacework.atlassian.net/browse/GROW-2616
> chore: verify and update examples script to ensure they work

- laceworksdk/http_session.py
SDK version was not in user agent string
Testing:
Checked Honeycomb and verified user agent string
Issue:
https://lacework.atlassian.net/browse/GROW-1512
> fix: SDK version in user agent string

- .github/workflows/python-publish.yml
- .github/workflows/python-release.yml
Switch from using the python-semantic-release action to running it in a script. 
Issue:
https://lacework.atlassian.net/browse/GROW-2746
> ci(release): update github release action

- .github/workflows/python-release.yml
Checkout action needs version bump and persist-credentials turned off
> ci(release): update checkout action in release workflow

- .github/workflows/python-publish.yml
- .github/workflows/python-release.yml
Turn off pypi publish workflow and add to release workflow
> ci(release): add PyPI publish to release action

- .github/workflows/python-release.yml
This is necessary to create release
> ci(release): add token to version step

- .github/workflows/python-test.yml
- laceworksdk/api/v2/vulnerabilities.py
- tests/api/v2/test_vulnerabilities.py
Reverts lacework/python-sdk#169
> Revert "feat: Support Image Summary API for Box"
